project:
  type: website

website:
  navbar:
    logo: resources/uu_blacktext.png
    logo-href: "https://www.uu.nl/"
    left:
      - href: index.qmd
        text: MATILDA
      - href: quiz.qmd
        text: Where do I start?
      - href: experts.qmd
        text: Our experts
  sidebar:
    style: "docked"
    contents:
      - section: "Research Question/Aim"
        contents:
          - text: "[Different Goals - Description, Prediction, Causation, Understanding]"
          - text: "[Intraindividal Differences vs Interindividual Differences]"
      - section: "Substantive Theory"
        contents:
          - href: TScale_General.qmd
            text: "Time Scale"
          - href: Distributions_General.qmd
            text: "Distribution"
          - text: "[Context and Events]"
      - section: "Measurement Theory"
        contents:
          - text: "[Conceptually Defining your Variable]"
          - href: ItemDesign_General.qmd
            text: "Item Design"
          - text: "[Measurement Modeling]"
          - href: Validation_General.qmd
            text: "Validation"
      - text: "---"
      - href: PageTemplate.qmd
        text: "Template Page"

format:
  html:
    theme:
      - custom.scss
    header-includes:
                  <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet"> 
    css: styles.css
    toc: true

editor: visual

