project:
  type: website

website:
  navbar:
    logo: resources/images/uu_blacktext.png
    logo-href: "https://www.uu.nl/"
    left:
      - href: index.qmd
        text: MATILDA
      - href: navigation.qmd
        text: Where do I start?
      - href: experts.qmd
        text: Our experts
  sidebar:
    style: "docked"
    contents:
      - section: "Research Question/Aim"
        contents:
          - text: "[Different Goals - Description, Prediction, Causation, Understanding]"
          - text: "[Intraindividal Differences vs Interindividual Differences]"
      - section: "Substantive Theory"
        contents:
          - href: substantive-theory/time-scales.qmd
            text: "Time Scale"
          - href: substantive-theory/distributions.qmd
            text: "Distributions"
          - text: "[Context and Events]"
      - section: "Measurement Theory"
        contents:
          - text: "[Conceptually Defining your Variable]"
          - href: measurement-theory/item-design.qmd
            text: "Item Design"
          - text: "[Measurement Modeling]"
          - href: measurement-theory/validation.qmd
            text: "Validation"
      - text: "---"
      - href: template.qmd
        text: "Template Page"

format:
  html:
    theme:
      - resources/styles/custom.scss
    header-includes: <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet"> 
    css: resources/styles/styles.css
    csl: resources/styles/apa.csl
    toc: true

editor: visual

